---
# defaults file for Dynac
dynac_pg_packages: 
  - postgresql94
  - postgresql94-contrib
  - postgresql94-devel
  - postgresql94-libs
  - postgresql94-server
  - slony1-94
  - python-psycopg2

dynac_pg_version: "94"
dynac_pg_home: "/var/lib/pgsql/9.4"
dynac_pg_service: "postgresql-9.4"
dynac_pg_bin: "/usr/pgsql-9.4/bin"
