---
#Install common packages and services here
#

#Separating the Development group from the other yum installs as it was conflicting on a man page.
- name: Install common packages 1
  yum: name={{ item }} state=latest
  with_items:
    - "@development"


- name: Install common packages 2
  yum: name={{ item }} state=latest 
  with_items:
    - dkms
    - kernel-devel
    - "@compat-libraries"
    - "@file-server"
    - "@ftp-server"
    - "@guest-agents"
    - "@input-methods"
    - "@multimedia"
    - "@print-client"
    - "@remote-system-management"
    - "@perl-runtime"
    - kexec-tools
    - perl-DBD-Pg
    - perl-CGI
    - openssh-askpass
    - httpd
    - tftp
    - ftp
    - zlib-devel
    - mutt
    - ntp
    - dbus-x11 
    - dconf-editor
    - xorg-x11-server-utils
    - rpm-build
    - subversion 
    - open-vm-tools 
    - python-pip
    - dos2unix
    - subversion
 
 #Probably need to remove this as soon as you prove out the DHCP switch
- name: Install firstboot service
  copy: src=etc/systemd/system/kapsch_firstboot.service dest=/etc/systemd/system/kapsch_firstboot.service mode=0700 owner=root group=root

- name: Install the scripts to support first boot
  copy: src=usr/local/bin/ dest=/usr/local/bin/ owner=root group=root mode=0750

- name: Enable firstboot service
  service: name=kapsch_firstboot enabled=yes

- name: Install common services 
  yum: name={{ item }} state=latest
  with_items:
    - vsftpd
    - ntp

- name: Configure NTPD
  template: src=etc/ntp.conf dest=/etc/ntp.conf mode=0644
  notify: NTPD restart

- name: Configure common services
  service: name={{ item }} state=running enabled=yes
  with_items:
    - vsftpd
    - ntpd

- name: Set the message of the day
  copy: src=etc/motd dest=/etc/motd mode=0644
- name: Configure i18n
  copy: src=etc/sysconfig/i18n dest=/etc/sysconfig/i18n  mode=0644

- name: Configure timezone
  command: ln -s /usr/share/zoneinfo/{{common_timezone}} /etc/localtime -f
