# -*- mode: ruby -*-
# vi: set ft=ruby :

$ansible_pre_script = <<SCRIPT
echo I am provisioning via script...
date > /tmp/vagrant_provisioned_at
#######################
#Setup Ansible
yum install -y epel-release
yum install -y ansible
chmod -R 777 /etc/ansible

#End of Ansible setup
#########################

############################################
#Setup users
#
echo "Setting up the initial users..."
#We are only setting up JUST enough access to allow the deploybot user to login and sudo.
sudo useradd dynac -u 2001
sudo useradd deploybot -G dynac -u 2002
#Setup private key login for deployment user...
mkdir /home/deploybot/.ssh
chmod 0700 /home/deploybot/.ssh
chown deploybot:deploybot /home/deploybot/.ssh
cat > /home/deploybot/.ssh/authorized_keys << EOF
PUT_ANY_REQUIRED_PUB_KEY_HERE 
EOF
chmod 0600 /home/deploybot/.ssh/authorized_keys
chown deploybot:deploybot /home/deploybot/.ssh/authorized_keys
#Modify suders file
sed -i '/requiretty/d' /etc/sudoers
#Setup base sudo file to allow ansible to do it's thing
cat > /etc/sudoers.d/custom << EOF
User_Alias  POWER_USERS=deploybot
POWER  ALL=(ALL) NOPASSWD: ALL
EOF
chmod 0640 /etc/sudoers.d/custom
#
#END OF USERS SETUP 
##############################################

#Clean yum cache
yum clean all
#End of Vagrant inline script
###################################
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |v|
    v.name = "kapsch_dynac"
  end


  #Configure VM settings
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end


  #Configure the proxy settings
  config.proxy.http     = "http://PROXY_IP:8090"
  config.proxy.https    = "http://PROXY_IP:8090"
  config.proxy.no_proxy = "localhost,127.0.0.1,172.0.0.0,172.20.151.152,yourdomain.com"
  

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos-7"
  
  #Run the inline script defined above
  config.vm.provision "shell", inline: $ansible_pre_script
  #Copy the ansible roles and site files
  config.vm.provision "file", source: "ansible/roles", destination: "/etc/ansible/"
  config.vm.provision "file", source: "ansible/sites", destination: "/etc/ansible/"
  #Run the ansible site
  config.vm.provision "shell", inline: "sudo ansible-playbook /etc/ansible/sites/site_single_vagrant.yml"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # We set it to virtual box due to rsync issues with Windows hosts.
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

end
