# -*- mode: ruby -*-
# vi: set ft=ruby :

$ansible_pre_script = <<SCRIPT
echo I am provisioning...
date > /tmp/vagrant_provisioned_at

#######################
#Setup Ansible
yum install -y epel-release
yum clean all
yum install -y ansible
chmod -R 777 /etc/ansible

#End of Ansible setup
#########################

############################################
#Setup users
#
#Moved to ansible
#
#END OF USERS SETUP 
##############################################

#Clean yum cache
yum clean all
#End of Vagrant inline script
###################################
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |v|
    v.name = "ansible_configured_vm"
  end


  #Configure VM settings
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end


  #Configure the proxy settings
  config.proxy.http     = "http://172.20.1.1:8090"
  config.proxy.https    = "http://172.20.1.1:8090"
  config.proxy.no_proxy = "localhost,127.0.0.1,172.0.0.0,192.168.0.0,mydomain.com"
  

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos-7"
  
  #Run the inline script defined above
  config.vm.provision "shell", inline: $ansible_pre_script
  #Copy the ansible roles and site files
  config.vm.provision "file", source: "ansible/roles", destination: "/etc/ansible/"
  config.vm.provision "file", source: "ansible/sites", destination: "/etc/ansible/"
  #Run the ansible site
  config.vm.provision "shell", inline: "sudo ansible-playbook /etc/ansible/sites/site_single_vagrant.yml"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # We set it to virtual box due to rsync issues with Windows hosts.
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

end
